config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :ideas do 
    resources :likes, shallow: true, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
  end
  # Defines the root path route ("/")
  # root "articles#index"
  root "ideas#index"

  resource :session, only:[:new, :create, :destroy]
  resources :users, only: [:new, :create]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

    alias_action :create, :read, :update, :delete, :to => :crud

    can :crud, Idea do |idea| 
        user == idea.user
    end

    can :crud, Review do |review| 
      user == review.user
    end

    can :like, Idea do |idea|
      user.persisted? && idea.user != user
    end

    can :destroy, Like do |like|
      like.user == user
    end
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/idea.rb
class Idea < ApplicationRecord
    belongs_to :user
    
    has_many :reviews, dependent: :destroy

    has_many :likes, dependent: :destroy
    has_many :likers, through: :likes, source: :user
    
    validates :title, presence: true

    validates :description, presence: true, length: {minimum: 50}
end

app/models/like.rb
class Like < ApplicationRecord

    belongs_to :user
    belongs_to :idea

    validates(
        :idea_id,
        uniqueness: {
            scope: :user_id,
            message: "Has already been liked"
        }
    )
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :idea
  belongs_to :user
  validates :body, presence: true, length: {minimum: 2}
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :ideas, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_ideas, through: :likes, source: :idea

    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX

    def full_name
        self.first_name + " " + self.last_name
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def current_user
        @current_user ||= User.find_by_id session[:user_id]
        
    end

    helper_method :current_user
    #helper_method makes the method also available for the views

    def user_signed_in?
        current_user.present?

    end

    helper_method :user_signed_in?

    def authenticate_user!
        redirect_to new_session_path, notice: "Please sign in" unless user_signed_in?
        
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    before_action :find_idea, only: [:edit, :update, :show, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    before_action :authorize_user!, only: [:edit, :update, :destroy]

   


    def index
        @ideas = Idea.all.order(created_at: :desc)
      
    end

    def show
        @reviews = @idea.reviews.order(created_at: :desc)
        @review = Review.new
    end


    def new
        @idea = Idea.new
    end

    def create
        @idea = Idea.new(idea_params)
        @idea.user = current_user
        if @idea.save
            flash[:success] = "Idea successfully created"
            redirect_to @idea
        else
            flash[:error] = "Something went wrong"
            render 'new', status: 303
        end
    end

    def edit

    end

    def update
        if @idea.update(idea_params)
            flash[:success] = "Idea successfully updated"
            redirect_to @idea
        else
            flash[:error] = "Something went wrong"
            render :edit, status: 303
        end
    end

    def destroy
        @idea.destroy
        redirect_to ideas_path
    end
    



    private

    def find_idea
      @idea = Idea.find params[:id]
    end

    def idea_params
        params.require(:idea).permit(:title, :description)
    end

    def authorize_user!
        redirect_to root_path, alert: "Not authorized" unless can?(:crud, @idea)
        
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!, only: [:create, :destroy]

    def create
        @idea = Idea.find params[:idea_id]
        @like = Like.new(idea: @idea, user: current_user)
        if can? :like, @idea
            if @like.save
                flash.notice = "Idea liked"
            else
                flash.alert = @like.errors.full_messages.join(", ")
            end
        else
            flash.alert = "You cannot like this idea"
        end
        redirect_to root_path
    end

    def destroy
       @like = current_user.likes.find params[:id] 
       if !can?(:destroy, @like)
        flash[:warning] = "You cannot destroy a like you don't own!"
       elsif @like.destroy
        flash[:success] = "Question Unliked"
       else
        flash[:warning] = "Couldn't Unlike the question..."
       end
       redirect_to root_path
    end
   
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_idea
    before_action :authenticate_user!
    def create
        @review = Review.new(review_params)
        @review.idea = @idea
        @review.user = current_user
        if @review.save
            flash[:success] = "Answer successfully created"
            redirect_to @idea
         else
            @reviews = @idea.reviews.order(created_at: :desc)
            render '/ideas/show', status: 303
        end
    end

    def destroy
        @review = Review.find params[:id]
        if can?(:crud, @review)
            @review.destroy
            redirect_to idea_path(@review.idea)
            flash[:success] = "Answer deleted"
        else
            redirect_to @idea, alert: "Not authorized"
        end
    end

    private

    def find_idea
        @idea = Idea.find params[:idea_id]
    end

    def review_params
        params.require(:review).permit(:body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
      @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, {notice: "Logged in"}
    else
      flash[:alert] = "Wrong Email or password"
      render :new, status: 303
    end
  end

  def destroy
    session[:user_id] = nil
    flash.notice = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new

    if user_signed_in?
      redirect_to root_path
    else
    @user = User.new
    end

  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash.notice = "Signed up!"
      redirect_to root_path
    else
      render :new, status: 303
    end

  end



  private
  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation
    )
  end

  def find_user
    @user = User.find params[:id]
  end
  def password_user
    @user = User.find params[:user_id]
  end

  def authorize_user!
    redirect_to root_path, alert: "Not authorized" unless can?(:crud, @user)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_with(model: @idea) do |form| %>
  <div class="p-3">
    <span style="font-size: 20px;"> <%= form.label :title%></span>
    <br>
    <%= form.text_field :title, style:"width:100%; margin-top:10px;" %>
  </div>
  <div class="p-3">
    <span style="font-size: 20px"><%= form.label :description %> </span>
    <br>
    <%= form.text_area :description, cols:50, rows: 5, style:"width:100%; margin-top:10px;" %>
  </div>
  <div class="p-3">
    <%= form.submit class: "btn btn-outline-success"%>
    <%=link_to "Cancel", root_path, class:"btn btn-outline-success"%>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<div style="margin-top: 10vh">
  <% if @idea.errors.any? %>
    <ul style="list-style-type: none;">
      <b>*Error: Please see below for more info* </b>
      <% @idea.errors.full_messages.each do |msg| %>
        <li style="color:red"> <%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_with(model: @idea) do |form| %>
    <div class="p-3">
      <span style="font-size: 20px;"> <%= form.label :title%></span>
      <br>
      <%= form.text_field :title, style:"width:100%; margin-top:10px;" %>
    </div>
    <div class="p-3">
      <span style="font-size: 20px"><%= form.label :description %> </span>
      <br>
      <%= form.text_area :description, cols:50, rows: 5, style:"width:100%; margin-top:10px;" %>
    </div>
    <div class="p-3">
      <%= form.submit class: "btn btn-outline-success" %>
      <%=link_to "Cancel", idea_path(@idea), class:"btn btn-outline-success"%>
    </div>
  <% end %>
</div>

app/views/ideas/index.html.erb
<div style="margin-top: 1vh">
  <%@ideas.each do |idea|%>
    <div class="card m-2">
      <div class="card-body">
        <h3 class="card-title"><%=link_to idea.title, idea, style:"text-decoration: none; color:#31817e"%></h3>
        <p class="card-text"><%=idea.description%></p>
        <div class="d-flex flex-row justify-content-end">
          <p style="flex:1"><small>By <%=idea.user.full_name%></small></p>
          <%like = idea.likes.find_by(user: current_user)%>
          <%if like.present?%>
            <%= button_to "Liked", like_path(like.id), method: :delete, class:"btn btn-success mx-3" %>
          <%else%>
            <%= button_to "Like", idea_likes_path(idea), method: :post, class:"btn btn-outline-success mx-3", style:"float:left;" %>
          <% end %>
          <p> Likes: <%=idea.likes.count%></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/ideas/new.html.erb
<div style="margin-top: 10vh">
  <% if @idea.errors.any? %>
    <ul style="list-style-type: none;">
      <b>*Error: Please see below for more info* </b>
      <% @idea.errors.full_messages.each do |msg| %>
        <li style="color:red"> <%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= render "form" %>
</div>

app/views/ideas/show.html.erb
<%=link_to "Back to Home Page", root_path, class:"btn btn-success m-3", style:"float:right;"%>
<h2 class="p-3" style=" color: #31817e"><%= @idea.title %></h2>
<p class = "p-3" ><%= @idea.description %></p>
<p class = "p-3">
  <small>Idea belongs to: <%=@idea.user.full_name%> <br>
  </small>
  <small>Number of likes: <%=@idea.likes.count%></small> <br>
  <small>Created at: <%= @idea.created_at %></small>
</p>
<div class="d-flex p-3">
  <%if can? :crud, @idea%>
    <%= button_to "Edit", edit_idea_path(@idea), method: :get, class: "btn btn-outline-success", style: "margin-right:5px;"%>
    <%= button_to 'Delete', idea_path(@idea), method: :delete, class: "btn btn-outline-success", form: {data: {turbo_confirm: "Are you sure?"}} %>
  <% end %>
</div>
<% if @review.errors.any? %>
  <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
  </ul>
<% end %>
<div class="p-3">
  <%=form_with(model: [@idea, @review]) do |f| %>
    <div>
      <span style="font-size:25px;"><%= f.label :body, "Review"%></span>
      <br>
      <%= f.text_area :body, rows: 5, :placeholder => " What's on your mind?", style: "width: 100%" %>
    </div>
    <%= f.submit "Submit", class: "btn btn-outline-success"%>
  <% end %>
</div>
<% @reviews.each do |review| %>
  <div class="p-3 d-flex flex-column" style="flex-wrap: wrap;">
    <p> <%= review.body %></p>
    <p style="font-size: 12.5px;">
      Reviewed <%= time_ago_in_words(review.created_at)%> ago by: <%=review.user.full_name%>
      <%if can? :crud, review%>•
        <%= link_to "Delete", idea_review_path(@idea.id,review.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, style: "text-decoration: none; color:#31817e " %>
      <% end %>
    </p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz 2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div style="margin-bottom:13vh">
      <nav class="navbar fixed-top navbar-dark" style="background-color:#266461; box-shadow: 0 0.5rem 1rem rgb(0 0 0 / 25%), inset 0 -1px 0 rgb(0 0 0 / 15%);">
        <a class="navbar-brand" href="<%=root_path%>">
          <%= image_tag ("logo3.png"), style: "width:15%; height: 100%; margin-left:3%; margin-right:2%"%>
          Idea Factory
        </a>
        <ul class="nav justify-content-end" style="margin-right:1vw;">
          <li class="nav-item">
            <a style="font-size:20px; color:white" class="nav-link" href="<%=ideas_path%>">Home</a>
          </li>
          <li class="nav-item">
            <a style="font-size:20px; color:white" class="nav-link" href="<%=new_idea_path%>">New Idea</a>
          </li>
          <%if user_signed_in?%>
            <li class="nav-item">
              <p class= "nav-link", style= "margin-right:1vw; font-size:20px; color:bisque"><%=current_user.full_name %></p>
            </li>
            <li class="nav-item">
              <%= button_to "Sign Out", session_path, method: :delete, class: "btn btn-success", style: "font-size:20px; color:white"%>
            </li>
          <%else%>
            <li class="nav-item">
              <a style="font-size:20px; color:white" class="nav-link" href="<%=new_session_path%>">Sign In</a>
            </li>
            <li class="nav-item">
              <a style="font-size:20px; color:white" class="nav-link" href="<%=new_user_path%>">Sign Up</a>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
    <% flash.each do |type, message| %>
      <div class="alert alert-info" role=alert >
        <%= type + "-------" + message %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div style="width:30vw;  text-align: center; padding-top: 10vh; margin: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);"" >
  <ul class="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="tab-login" data-mdb-toggle="pill" href="/session/new" role="tab"
      aria-controls="pills-login" aria-selected="true" style="color:#31817e">Login</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link active" id="tab-register" data-mdb-toggle="pill" href="/users/new" role="tab"
      aria-controls="pills-register" aria-selected="false">Sign Up</a>
    </li>
  </ul>
  <% if @user.errors.any?%>
    <p><%= @user.errors.full_messages.join(', ')%></p>
  <%end%>
  <%= form_with model: @user do |f|%>
    <div class="form-outline mb-4">
      <%= f.label :first_name, class: "form-label"%>
      <%= f.text_field :first_name, class: "form-control", style: "text-align: center;"%>
    </div>
    <div class="form-outline mb-4">
      <%= f.label :last_name, class: "form-label"%>
      <%= f.text_field :last_name, class: "form-control", style: "text-align: center;"%>
    </div>
    <div class="form-outline mb-4">
      <%= f.label :email, class: "form-label"%>
      <%= f.text_field :email, placeholder: "email@example.ca", class: "form-control", style: "text-align: center;"%>
    </div>
    <div class="form-outline mb-4">
      <%= f.label :password, class: "form-label"%>
      <%= f.password_field :password, placeholder: "Enter password", class: "form-control", style: "text-align: center;"%>
    </div>
    <div class="form-outline mb-4">
      <%= f.label :password_confirmation, class: "form-label"%>
      <%= f.password_field :password_confirmation, placeholder: "Re-Enter password", class: "form-control", style: "text-align: center;"%>
    </div>
    <%= f.submit "Sign Up",  class: "btn btn-success btn-block mb-3", style: "width: 20%" %>
  <%end%>
</div>